// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsToml.fsproj")>]
[<assembly: AssemblyProductAttribute("fstoml")>]
[<assembly: AssemblyDescriptionAttribute("TOML based F# Project System")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsToml.fsproj"
    let [<Literal>] AssemblyProduct = "fstoml"
    let [<Literal>] AssemblyDescription = "TOML based F# Project System"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
